name: CI for Mobile Auto tests

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  on_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'oracle'
          java-version: '21'
          
      # Set up Android SDK
      - name: Set up Android SDK
        run: |
          echo "Downloading Android SDK..."
          sudo apt-get update
          sudo apt-get install -y android-sdk
          echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
      
      # Set up Nodejs
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      # Set up and Run Appium
      - name: Start Appium Server
        run: |
          npm install -g appium@latest
          appium driver install uiautomator2
          appium plugin install images
          appium &

      # Start an Android Emulator and Run Tests
      - name: Android Emulator Runner and Run Tests
        uses: ReactiveCircus/android-emulator-runner@v2.33.0
        with:
          api-level: 33
          profile: 'Nexus 6'
          target: google_apis
          arch: x86_64
          script: |
            adb install src/test/resources/apps/base.apk
            mvn clean test
